name: WormholeXTreme
main: de.luricos.bukkit.WormholeXTreme.Wormhole.WormholeXTreme
version: 1.2
api-version: 1.13
authors: [Lologarithm, alron, lycano, Zytharian, Sir-Dizzle]
softdepend: [Help]
description: >
             Wormhole X-Treme! Wormholes as travel portals. Splash Effect, IDC,
             Iris, configurable Wormhole materials, and much much more.

commands:
   dial:
     description: Dial a remote Stargate, unlock IDC with optional password
     usage: |
            /<command> <StarGate> [IDC]
            <stargate> The StarGate to dial.
            [IDC] Use optional password to open remote Iris.

   wormhole:
     description: Wormhole administration and configuration commands.
     aliases: [wxt]
     usage: |
            /<command> activate_timeout [timeout] - Set or get the stargate activate timeout.
            /<command> custom <stargate|-all> <boolean> - Set Gate to custom mode.
            /<command> irismaterial <stargate> [material] - Set the Iris-Material for stargate.
            /<command> lightmaterial <stargate> [material] - Set the Chevron Light-Up Material for stargate to material.
            /<command> owner <stargate> <new owner> - Set a new owner for stargate.
            /<command> perms - This command is currently disabled.
            /<command> permissions <provider> - Get or set permissions provider.
            /<command> portalmaterial <stargate> [material] - Set the Portal-Material for stargate.
            /<command> restrict <value> [count] - Get or set restriction count for value where value is group, true or false.
            /<command> regenerate <stargate> [boolean] - Enable/Disable auto-regeneration for stargate.
            /<command> redstone <stargate> [boolean] - Set or get redstone gate information.
            /<command> shutdown_timeout [timeout] - Set or get the stargate shutdown timeout.
            /<command> show_gwm - Show current welcome message status
            /<command> show_transport - Show current set Transportation method.
            /<command> simple [yes, no] - Enable or disable simple permissions.
            /<command> toggle_gwm - Toggle stargate welcome message
            /<command> toggle_transport - Toggle Transportation method. Toggles between EVENT, TELEPORT.
            /<command> wooshdepth <stargate> [depth] - Get or set wooshdepth for stargate.
   wxlist:
     description: List all Stargates.
     usage: |
            /<command> - List all Stargates.

   wxbuild:
     description: Automatically Build Stargate.
     usage: |
            /<command> <GateShape>
            <GateShape> The GateShape to build.
            After placing a DHD with a button (and sign if wanted) running this command then pressing the button will cause the specified <GateShape> to be built.

   wxbuildlist:
     description: List available gate shapes
     usage: |
            /<command>

   wxremove:
     description: Remove a stargate, optionally destroy its blocks.
     usage: |
            /<command> <GateName> [-all]
            <GateName> The GateName to remove.
            [-all] destroys gate blocks too.

   wxcompass:
     description: Point compass needle at nearest Stargate.
     usage: |
            /<command> - Point compass needle at nearest Stargate.

   wxcomplete:
     description: Complete StarGate construction.
     usage: |
            /<command> <GateName> idc=[IDC] net=[Net]
            <GateName> The name to give new Stargate.
            [IDC] Optional password to give Stargate.
            [Net] Optional network for Stargate.

   wxidc:
     description: Gets or sets a gates IDC code.
     usage: |
            /<command> <GateName> <optional_set_idc>
            Requires being either owner or have wormhole.config
            set -clear to remove the IDC

   wxforce:
     description: Forcefully shut down, darken, and open the iris of either a single or all gates.
     usage: |
            /<command> <gateName|-all>

   wxgo:
     description: Teleport to specified wormhole.
     usage: |
            /<command> <GateName>

   wxreload:
     description: Reload WormholeXTreme
     aliases: [wxre]
     usage: |
            /<command> <commandType> - Reload WormholeXTreme
            Valid commandtypes - n(ow)

   wxstatus:
     description: Show system status
     aliases: [wxs]
     usage: |
            /<command> <commandType> - Show status
            Valid commandtypes - a(ll)

permissions:
  wormhole.use.sign:
    description: Player is able to use the dialer sign
    default: true
  wormhole.use.dialer:
    description: Player is able to use the dialer
    default: true
  wormhole.use.compass:
    description: Can use the wormhole compass
    default: true
  wormhole.use.*:
    description: Can use all wormhole use nodes
    children:
      wormhole.use.sign: true
      wormhole.use.dialer: true
      wormhole.use.compass: true
  wormhole.cooldown.groupone:
    description: Use cooldown group one
    default: false
  wormhole.cooldown.grouptwo:
    description: Use cooldown group two
    default: false
  wormhole.cooldown.groupthree:
    description: Use cooldown group three
    default: false
  wormhole.cooldown.*:
    description: Can use all cooldown nodes
    children:
      wormhole.cooldown.groupone: true
      wormhole.cooldown.grouptwo: true
      wormhole.cooldown.groupthree: true
  wormhole.remove.own:
    description: Can remove own gates
    default: op
  wormhole.remove.all:
    description: Can remove a gate using -all command
    default: op
  wormhole.remove.*:
    description: Can use all remove permissions
    children:
      wormhole.remove.own: true
      wormhole.remove.all: true
  wormhole.build:
    description: Can build Wormhole
    default: op
  wormhole.build.groupone:
    description: Build restriction for groupone
    default: false
  wormhole.build.grouptwo:
    description: Build restriction for grouptwo
    default: false
  wormhole.build.groupthree:
    description: Build restriction for groupthree
    default: false
  wormhole.build.*:
    description: Can use all build permissions
    children:
      wormhole.build: true
      wormhole.build.groupone: true
      wormhole.build.grouptwo: true
      wormhole.build.groupthree: true
  wormhole.config:
    description: Can modify Wormhole config
    default: op
  wormhole.list:
    description: Can list wormhole gates
    default: true
  wormhole.network.use:
    description: Can use gate network
    default: true
  wormhole.network.build:
    description: Can build networks
    default: op
  wormhole.network.*:
    description: Can use all network permissions
    children:
      wormhole.network.use: true
      wormhole.network.build: true
  wormhole.go:
    description: Can teleport to a wormhole location
    default: op
  wormhole.simple.use:
    description: Can use wormhole
    default: true
  wormhole.simple.config:
    description: Can modify configuration
    default: op
  wormhole.simple.build:
    description: Can build a wormhole
    default: op
  wormhole.simple.remove:
    description: Can remove a wormhole
    default: op
  wormhole.simple.*:
    description: Can use all simple wormhole nodes
    children:
      wormhole.simple.config: true
      wormhole.simple.build: true
      wormhole.simple.remove: true
      wormhole.simple.use: true